# Generated by Django 6.0.4 on 2026-04-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='account_type',
            field=models.CharField(choices=[('demo', 'Demo'), ('real', 'Real')], default='demo', max_length=10),
        ),
    ]
