# Generated by Django 6.0.4 on 2026-04-25 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_google_id_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_account',
            field=models.CharField(choices=[('demo', 'Demo'), ('real', 'Real')], default='demo', max_length=10),
        ),
        migrations.AddField(
            model_name='wallet',
            name='account_type',
            field=models.CharField(choices=[('demo', 'Demo'), ('real', 'Real')], default='demo', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'account_type')},
        ),
    ]
