# Generated by Django 6.0.4 on 2026-04-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
